// import { Inter } from "next/font/google";
import "tailwindcss/tailwind.css";
import "./main.css";
import Head from "next/head";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "AFIT Digital Hub",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Head>
                <link rel="icon" href="/adhp-1.png" sizes="any" />
            </Head>

            <body>{children}</body>
        </html>
    );
}
